import localFont from "next/font/local";
import "../globals.css";
import Sidebar from "./sidebar/sidebar";
import Navbar from "./navbar/navbar";
import { AuthProvider } from "@/Provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Admin | Fmconsultants",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ToastContainer />
      <Navbar />
      <div className=" flex justify-center items-center">
        <AuthProvider> {children}</AuthProvider>
      </div>
      <div className="w-64">
        <Sidebar />
      </div>
    </div>
  );
}
